version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mcp-mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptest"]
      interval: 5s
      timeout: 5s
      retries: 5
